service: mini-hms-email

provider:
  name: aws
  runtime: python3.9
  environment:
    GMAIL_USER: aniketchakraborty808@gmail.com
    GMAIL_PASS: your_app_password_here

functions:
  sendEmail:
    handler: handler.handler
    events:
      - http:
          path: send-email
          method: post
